config/routes.rb
Rails.application.routes.draw do
  # User routes
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  # Application and events routes  
  resources "registrated_applications"
  namespace :api, defaults: { format: :json } do 
    resources :events, only: [:create]
  end
  # Root to home page for new user
  root 'welcome#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registrated_application
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user

  # Validations
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, scope: :provider

  # Create Indentities for each user
  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end

end

app/models/registrated_application.rb
class RegistratedApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  TEMP_EMAIL_PREFIX = "change@me" # sets the twitter users temporary e-mail
  TEMP_EMAIL_REGEX = /\Achange@me/ # evaluates the twitters users email to ensure they are not be signed-in with a temporary e-mail

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, 
         :omniauth_providers => [:facebook, :twitter]

  # Validations for log-in details
  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  # Model relationships
  has_many :identities, dependent: :destroy
  has_many :registrated_applications, dependent: :destroy

  def self.find_for_oauth(auth, signed_in_resource = nil)

    identity = Identity.find_for_oauth(auth)
    user = signed_in_resource ? signed_in_resource : identity.user
    
    if user.nil?
      email_is_verified = auth.info.email
      email = auth.info.email if email_is_verified
      user = User.where(email: email).first if email

      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end  

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!

  def create
    @registered_application = RegistratedApplication.find_by(url: request.env["HTTP_ORIGIN"])
    if @registered_application == nil
      render json: "Unregistered Application", status: :unprocessable_entity 
    else
      @event = @registered_application.events.build(event_params)
      if @event.save
        render json: @event, status: :created
      else
        render @event.errors, status: :unprocessable_entity
      end
    end
  end

  protected

  def event_params
    params.require(:event).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :ensure_signup_complete, only: [:new, :create, :update, :destroy]
  before_action :authenticate_user!

  protected

  def ensure_signup_complete
    return if action_name == "finish_signup"

    if current_user && !current_user.email_verified?
      redirect_to finish_signup_path(current_user)
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:name, :email]
    devise_parameter_sanitizer.for(:account_update) << [:name, :email]
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  include Devise::Controllers::Rememberable

  def self.provides_callback_for(provider)
    class_eval %Q{
      def #{provider}
        @user = User.find_for_oauth(env["omniauth.auth"], current_user)
        if @user.persisted?
          remember_me(@user)
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
        else
          session["devise.#{provider}_data"] = env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end
    }
  end

  [:twitter, :facebook].each do |provider|
    provides_callback_for provider
  end

  def after_sign_in_path_for(resource)
    if resource.email_verified?
      super resource
    else
      finish_signup_path(resource)
    end
  end

end

app/controllers/registrated_applications_controller.rb
class RegistratedApplicationsController < ApplicationController
  before_action :set_app, only: [:show, :edit, :update, :destroy]

  def index
    @apps = RegistratedApplication.all
  end

  def show  
    @event = @app.events.group_by(&:name)
  end

  def new
    @app = RegistratedApplication.new
  end

  def create
    @app = current_user.registrated_applications.build(app_params)
    respond_to do |format|
      if @app.save
        format.html {redirect_to @app}
        flash[:notice] = "Your #{@app.name} has been successfully registered"
      else
        format.html {render action: "new"}
        flash[:alert] = "Your app was not successfully registered. Please try again."
      end
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @app.update(app_params)
        format.html {redirect_to @app}
        flash[:notice] = "Your app was successfully updated"
      else
        format.html {render action: "edit"}
        flash[:alert] = "Your app was not successfully updated. Please try again."
      end
    end
  end

  def destroy
    respond_to do |format|
      if @app.destroy
        format.html {redirect_to registrated_applications_path}
        flash[:notice] = "Your app was succesfully deleted."
      else
        format.html {render action: "show"}
        flash[:alert] = "Your app was not successfully deleted. Please try again."
      end
    end
  end

  protected

  def set_app
    @app = RegistratedApplication.find(params[:id])
  end

  def app_params
    params.require(:registrated_application).permit(:name, :url)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :update, :finish_signup ]

  def update
    if @user.update(user_params)
      sign_in(@user == current_user ? @user : current_user, bypass: true)
      flash[:info] = "You have updated your user profile succesfully"
      redirect_to edit_user_registration_path
    else
      flash[:error] = "Your credentials were not updated successfully. Please try again!"
      render @user.errors
    end
  end

  def finish_signup
    if request.patch? && params[:user]
      if @user.update(user_params)
        sign_in(@user, bypass: true)
        redirect_to edit_user_registration_path
        flash[:info] = "You have registered successfully with Twitter"
      else
        @show_errors = true
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    accessible = [ :name, :email ]
    accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
    params.require(:user).permit(accessible)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrated_applications_helper.rb
module RegistratedApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Metrics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "partials/navbar" %>
  <%= render "partials/flash" %>
  <%= yield %>
  <%= render "partials/footer" %>
</body>
</html>

app/views/partials/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <button class="close" type="button" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-danger">
    <button class="close" type="button" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>  
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-warning">
    <button class="close" type="button" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>  
  </div> 
<% end %>  

app/views/partials/_footer.html.erb
<footer class="footer">
  <div class="container">
    <br>
    <p class="text-muted">Blocmetrics by Alexander Lewis</p>
  </div>
</footer>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-main">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
      <%= link_to "Blocmetrics", "#", class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_path %></li>
        <% if current_user %>
          <li><%= link_to "Registered Apps", registrated_applications_path %></li> 
        <% end %>
      </ul> 
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li>
          <%= link_to edit_user_registration_path do %> 
            <span class="glyphicon glyphicon-user"></span> <%= current_user.name %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <span class="glyphicon glyphicon-log-out"></span> Sign Out  
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to new_user_session_path do %>
            <span class="glyphicon glyphicon-log-in"></span> Sign In
          <% end %>
        </li>
      <% end %>
      </ul>  
    </div>
  </div>
</nav>

app/views/registrated_applications/_form.html.erb
<%= form_for @app do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", id: "inputPassword" %>
    <br>
    <%= f.label :url %>
    <%= f.text_field :url, class: "form-control", id: "inputPassword" %>
    <br>
    <%= f.button "create", class: "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner'></i>Creating......"} %>
<% end %>

app/views/registrated_applications/edit.html.erb
<div class="container">
  <div class="form-signin">
    <h2>Edit <%= @app.name %></h2>
    <%= render partial: "registrated_applications/form" %>  
  </div>
</div>

app/views/registrated_applications/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2">
      <div class="media">
        <div class="media-heading">
          <%= link_to "Register App", new_registrated_application_path, class: "btn btn-sm btn-success pull-right register-app" %>    
        </div>
      </div>
    </div>
    <div class="col-md-10">
      <% @apps.each do |app| %>
        <div class="media">
          <div class="media-heading">
            <h3><%= link_to "#{app.name}", registrated_application_path(app) %></h3>        
          </div>
          <div class="media-body">
            <h4><%= link_to "#{app.url}", app.url %></h4>
            <h4><%= app.events.count %></h4>          
          </div>
        </div>
      <% end %>
    </div>
    
  </div>
</div>

  

app/views/registrated_applications/new.html.erb
<div class="container">
  <h2>Register a new application</h2>
  <%= render partial: "registrated_applications/form" %>
</div>

app/views/registrated_applications/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= link_to "Edit", edit_registrated_application_path(@app), class: "btn btn-warning btn-sm pull-right register-app" %>
      <%= link_to "Delete", registrated_application_path(@app), class: "btn btn-danger btn-sm pull-right register-app", method: :delete, data: {confirm: "Are you sure you wish to deregister this app"} %>
    </div>
    <div class="col-md-9">
      <div class="media">
        <div class="media-heading">
          <h2><%= @app.name %></h2>
        </div>
        <div class="media-body">
          <h4><%= link_to "#{@app.url}", @app.url %></h4>          
          <% @event.each do |event, instance| %>
            <h4><%= "Event name: #{event}" %></h4>
            <h4><%= "Number of events: #{instance.count}" %></h4>
          <% end %>
        </div>
        <div>
          <%= pie_chart @app.events.group(:name).count %>
        </div>
        <div>
        <% if Rails.env.production? %>
          <%= line_chart @app.events.group_by_day(:created_at).count %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/finish_signup.html.erb
<div class="container">
  <div class="form-signin" id="sign-in-body">
    <%= form_for(current_user, as: "user", url: finish_signup_path(current_user), html: {role: "form"}) do |f| %>
      <h2 class="form-signin-heading">Add Email</h2>
      <% if @show_errors = true && current_user.errors.any? %>
        <div>
          <% current_user.errors.full_messages.each do |msg| %>
            <%= msg %>
          <% end %>
        </div>
      <% end %>
        <%= f.email_field :email, autofocus: true, value: "", placeholder: "email@me.com", id: "inputEmail", class: "form-control" %>
        <h5>Please confirm your email address to continue.</h5>
        <%= f.button "Continue", class: "btn btn-large btn-primary btn-block", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Sending email..."} %>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Welcome to Blocmetrics</h1>
    <p>Blocmetrics is an application that allows users to track events on their own web sites. Sign-up for a free account and get first-class analytics and metrics of significant events that occur on your websites and applications.</p>
    <p><%= link_to "Sign up", new_user_registration_path, class: "btn btn-lg btn-primary" %></p>
  </div>
</div>